# Your Solution

version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: project3_ydqn_user
      POSTGRES_PASSWORD: sbCO6IvVtcCmNLtl3u8iwWIagnMoHnyA
      POSTGRES_DB: project3_ydqn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  book_catalog:
    build: ./book_catalog
    container_name: book_catalog
    environment:
      DATABASE_URL: "postgresql://project3_ydqn_user:sbCO6IvVtcCmNLtl3u8iwWIagnMoHnyA@dpg-cr80s2dsvqrc73dmgk00-a.oregon-postgres.render.com/project3_ydqn"
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  inventory_management:
    build: ./inventory_management
    container_name: inventory_management
    environment:
      DATABASE_URL: "postgresql://project3_ydqn_user:sbCO6IvVtcCmNLtl3u8iwWIagnMoHnyA@dpg-cr80s2dsvqrc73dmgk00-a.oregon-postgres.render.com/project3_ydqn"
    ports:
      - "8001:8001"
    depends_on:
      - postgres
volumes:
  postgres_data:
